Oscar dev4
INDEP2022/f-sigebi pull request #1847
Opened 2023-06-02 22:41 UTC by Osc4r1b4rra

Se actualiza la pagina de cambio de texto

2023-06-02 22:44 UTC, genaroadrian approved these changes

2023-06-02 23:00 UTC, jessicaorozco approved these changes

2023-06-02 23:00 UTC, jessicaorozco approved these changes

2023-06-02 23:00 UTC, jessicaorozco approved these changes

2023-06-02 23:01 UTC, jessicaorozco requested changes
resol ver conflictos

2023-06-03 00:01 UTC, jessicaorozco approved these changes

2023-06-03 00:12 UTC, genaroadrian approved these changes

2023-06-03 00:13 UTC, merged