Destino
INDEP2022/f-sigebi pull request #4176
Opened 2023-09-22 20:02 UTC by NCatariMamani

2023-09-22 20:17 UTC, genaroadrian approved these changes

2023-09-22 20:18 UTC, genaroadrian reviewed
conflictos

2023-09-22 21:29 UTC, jessicaorozco approved these changes

2023-09-22 21:30 UTC, jessicaorozco requested changes
resolver conflictos

2023-09-23 14:28 UTC, HenryGiovanniSanchezSolis approved these changes

2023-09-24 00:54 UTC, jessicaorozco approved these changes

2023-09-24 00:54 UTC, merged