ajustes Validación Cálculo I.V.A
INDEP2022/f-sigebi pull request #4206
Opened 2023-09-29 13:24 UTC by LuissMontoya

ajustes Validación Cálculo I.V.A

2023-09-29 13:29 UTC, jessicaorozco approved these changes

2023-10-03 16:11 UTC, genaroadrian approved these changes

2023-10-03 16:13 UTC, devm02 approved these changes

2023-10-03 16:14 UTC, genaroadrian requested changes
Conflictos

2023-10-03 16:18 UTC, genaroadrian approved these changes
Conflictos

2023-10-03 16:18 UTC, merged